Mvc
LostLizard/category-service pull request #3
Opened 2022-03-26 21:05 UTC by LostLizard

2022-03-27 16:27 UTC, chenko16 requested changes

2022-03-27 16:27 UTC, chenko16 commented on src/main/java/com/example/categoryservice/controller/CategoryController.java
> +    @GetMapping("getById")
Так не пишется. Погугли спецификацию рестовых ручек.
Во-первых, забыл `/` в начале. Во вторых, лучше сделать так `category/get/{id}`, то есть id будет идти не как параметр, а как часть адреса. В спринге для этого есть @PathVariable
А получение всех категорий будет просто по урлу `/category/get`
Плюс ты не указал, что именно мы получаем, урл должен отражать семантику

2022-03-27 16:27 UTC, chenko16 commented on src/main/java/com/example/categoryservice/controller/CategoryController.java
> +        return new ResponseEntity<Category>(categoryService.getCategoryById(id), HttpStatus.OK);
Можно переписать красивее  `ResponseEntity.of(...)`. Плюс `HttpStatus.OK` итак по дефолту ставится

2022-03-27 16:27 UTC, chenko16 commented on src/main/java/com/example/categoryservice/controller/CategoryController.java
> -    @GetMapping("/list")
Вот `/list` тоже вариант, зря поменял

2022-03-27 16:27 UTC, chenko16 commented on src/main/java/com/example/categoryservice/controller/CategoryController.java
> +    @DeleteMapping("remove")
Здесь сделать по аналогии с get по id

2022-03-27 16:27 UTC, chenko16 commented on src/main/java/com/example/categoryservice/dao/repository/CategoryRepository.java
> +    @Override
Договорились же убрать `@Override`

2022-03-27 16:27 UTC, chenko16 commented on src/main/java/com/example/categoryservice/dto/Category.java
> +    public static Category replaceEntityOnSurfaceCategory(CategoryEntity categoryEntity){
А зачем этот метод? Это же по сути конструктор

2022-03-27 16:27 UTC, chenko16 commented on src/main/java/com/example/categoryservice/service/CategoryService.java
> +    void removeCategory(Category category);
Зачем тебе всю категорию передавать? Достаточно только id

2022-03-27 16:27 UTC, chenko16 commented on src/main/java/com/example/categoryservice/service/CategoryServiceImpl.java
> +    public void createCategory(Category category){
Зачем эта перегрузка? Это можно было бы сделать и в конструкторе. Да и не понятно, зачем принимать на вход параметры по отдельности. У тебя с фронта должна приходить форма, которая уже инкапсулирована в объект. Её и передавай

2022-03-27 16:27 UTC, chenko16 commented on src/main/java/com/example/categoryservice/service/CategoryServiceImpl.java
> +    public void updateCategory(Category category, Integer parentId){
То же самое, что и с create

2022-03-27 16:27 UTC, chenko16 commented on src/main/java/com/example/categoryservice/service/CategoryServiceImpl.java
> +    public void removeCategory(Category category){
Зачем этот метод? Удаление всегда должно быть по id

2022-03-27 16:27 UTC, chenko16 commented on src/main/java/com/example/categoryservice/service/CategoryServiceImpl.java
> +    public void updateCategory(Category category, Integer parentId){
Потерял `@Override`. Проверь соответствие интерфейса и класса

2022-03-27 16:30 UTC, LostLizard commented on src/main/java/com/example/categoryservice/dto/Category.java
> +    public static Category replaceEntityOnSurfaceCategory(CategoryEntity categoryEntity){
потому что конструктор принимающий entity уже есть, и он создает deep Category

2022-03-27 16:30 UTC, LostLizard commented on src/main/java/com/example/categoryservice/dao/repository/CategoryRepository.java
> +    @Override
убрал

2022-03-27 16:35 UTC, chenko16 commented on src/main/java/com/example/categoryservice/dto/Category.java
> +    public static Category replaceEntityOnSurfaceCategory(CategoryEntity categoryEntity){
Мы обсуждали, что надо сделать два конструктора в этом случае. Первый - принимает всю категорию (для глубокого копирования), а второй принимает параметры по отдельности

2022-03-30 12:52 UTC, LostLizard commented on src/main/java/com/example/categoryservice/controller/CategoryController.java
> +    @GetMapping("getById")
добавил RequestMapping /category и PathVariable где используется id. Нормально?

2022-03-30 21:31 UTC, chenko16 approved these changes

2022-03-30 21:31 UTC, chenko16 commented on src/main/java/com/example/categoryservice/dao/entity/CategoryEntity.java
>          this.getParentCategory().getSubCategories().remove(this);
А нужно ли выполнять эту и последнюю строчку? По идее достаточно просто сделать `this.setParentCategory(newParent);`, все остальное сделает hibernate. Проверь

2022-03-30 21:31 UTC, chenko16 commented on src/main/java/com/example/categoryservice/dto/Category.java
> +    private Category parentCategory;
Так и оставил и parentId и parentCategory, должно быть что-то одно, дублируется информация

2022-03-30 21:31 UTC, chenko16 commented on src/main/java/com/example/categoryservice/dto/Category.java
> +        if (category.getParentCategory()!=null) {
Можно переписать на Optional и ниже тоже

2022-03-30 21:31 UTC, chenko16 commented on src/main/java/com/example/categoryservice/service/CategoryServiceImpl.java
> +                .map((el) -> {
Громоздкий код. У тебя всего одна строчка в map, поэтому можно просто
`.map((el) ->  new Category(el.getId(), el.getName(), el.getDescription()))`

2022-03-30 21:31 UTC, chenko16 commented on src/main/java/com/example/categoryservice/service/CategoryServiceImpl.java
> +        if (category.getParentCategory().getId() == 0) {
Это что такое?? Почему 0?

2022-03-30 21:31 UTC, chenko16 commented on src/main/java/com/example/categoryservice/dao/entity/CategoryEntity.java
> +//TODO исследовать n+1 trouble query
Посмотрел этот момент?

2022-04-01 10:45 UTC, LostLizard commented on src/main/java/com/example/categoryservice/dao/entity/CategoryEntity.java
> +//TODO исследовать n+1 trouble query
я беру sublist сразу, не вызываю по одному, даже явно написал FetchType.Eager еще погуглю этот момент, мб есть скрытые камни

2022-04-01 10:45 UTC, LostLizard commented on src/main/java/com/example/categoryservice/service/CategoryServiceImpl.java
> +        if (category.getParentCategory().getId() == 0) {
вот тут был вопрос, в бд же можется создаться столбец с 0 id? у меня примитив вместо Integer, поэтому я так проверяю на отсутствие

2022-04-01 10:47 UTC, LostLizard commented on src/main/java/com/example/categoryservice/dto/Category.java
> +        if (category.getParentCategory()!=null) {
принимать Optional<CategoryEntity> в конструктор?

2022-04-01 18:31 UTC, merged